CREATE OR REPLACE TYPE "WM_CONCAT_TYPE"
AUTHID CURRENT_USER AS OBJECT
(
  CURR_STR VARCHAR2(32767),
  STATIC FUNCTION ODCIAGGREGATEINITIALIZE(SCTX IN OUT SGM_WM_CONCAT_TYPE) RETURN NUMBER,
  MEMBER FUNCTION ODCIAGGREGATEITERATE(SELF IN OUT SGM_WM_CONCAT_TYPE,
               P1 IN VARCHAR2) RETURN NUMBER,
  MEMBER FUNCTION ODCIAGGREGATETERMINATE(SELF IN SGM_WM_CONCAT_TYPE,
                                 RETURNVALUE OUT VARCHAR2,
                                 FLAGS IN NUMBER)
                     RETURN NUMBER,
  MEMBER FUNCTION ODCIAGGREGATEMERGE(SELF IN OUT SGM_WM_CONCAT_TYPE,
                    SCTX2 IN  SGM_WM_CONCAT_TYPE) RETURN NUMBER
);
/
CREATE OR REPLACE TYPE BODY "SGM_WM_CONCAT_TYPE"
IS
  STATIC FUNCTION ODCIAGGREGATEINITIALIZE(SCTX IN OUT SGM_WM_CONCAT_TYPE)
  RETURN NUMBER
  IS
  BEGIN
    SCTX := SGM_WM_CONCAT_TYPE(NULL) ;
    RETURN ODCICONST.SUCCESS;
  END;
  MEMBER FUNCTION ODCIAGGREGATEITERATE(SELF IN OUT SGM_WM_CONCAT_TYPE,
          P1 IN VARCHAR2)
  RETURN NUMBER
  IS
  BEGIN
    IF(CURR_STR IS NOT NULL) THEN
      CURR_STR := CURR_STR || ',' || P1;
    ELSE
      CURR_STR := P1;
    END IF;
    RETURN ODCICONST.SUCCESS;
  END;
  MEMBER FUNCTION ODCIAGGREGATETERMINATE(SELF IN SGM_WM_CONCAT_TYPE,
                                 RETURNVALUE OUT VARCHAR2,
                                 FLAGS IN NUMBER)
    RETURN NUMBER
  IS
  BEGIN
    RETURNVALUE := CURR_STR;
    RETURN ODCICONST.SUCCESS;
  END;
  MEMBER FUNCTION ODCIAGGREGATEMERGE(SELF IN OUT SGM_WM_CONCAT_TYPE,
                                   SCTX2 IN SGM_WM_CONCAT_TYPE)
  RETURN NUMBER
  IS
  BEGIN
    IF(SCTX2.CURR_STR IS NOT NULL) THEN
      SELF.CURR_STR := SELF.CURR_STR || ',' || SCTX2.CURR_STR ;
    END IF;
    RETURN ODCICONST.SUCCESS;
  END;
END;
/
